### ISSUE TITLE
Fluentd pod is crashing frequently

### ISSUE THREAD

**Issue by sjutz** [Gepardec/Hogarama#128]

**Comment by sjutz** [comment]
Problem should be fixed with newer version of fluentd. Updating fluentd led to errors in authentification, the username specified in fluentd.conf is not recognized. Probably syntax of fluentd.conf has changed with newer fluentd-version. We also tried different fluent-plugin-mqtt-io version, but without success. It needs to be determined which versions of fluentd and fluent-plugin-mqtt-io are compatible.

**Comment by sjutz** [comment]
Original errormessage:

2018-02-02 12:53:23 +0100 [info]: fluent/log.rb:322:info: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2018-02-02 12:53:23 +0100 [warn]: [output_docker1] 'time_format' specified without 'time_key', will be ignored
2018-02-02 12:53:23 +0100 [warn]: [output1] 'time_format' specified without 'time_key', will be ignored
2018-02-02 12:53:23 +0100 [debug]: fluent/log.rb:302:debug: adding store type="mongo"
2018-02-02 12:53:24 +0100 [info]: fluent/log.rb:322:info: 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
2018-02-02 12:53:24 +0100 [warn]: fluent/log.rb:342:warn: Since v0.8, invalid record detection will be removed because mongo driver v2.x and API spec don't provide it. You may lose invalid records, so you should not send such records to mongo plugin
2018-02-02 12:53:24 +0100 [debug]: fluent/log.rb:302:debug: Setup mongo configuration: mode = normal
2018-02-02 12:53:24 +0100 [debug]: fluent/log.rb:302:debug: adding store type="file"
2018-02-02 12:53:24 +0100 [warn]: [mqttoutput] 'time_format' specified without 'time_key', will be ignored
/var/lib/gems/2.3.0/gems/fluent-plugin-mqtt-io-0.2.3/lib/fluent/plugin/in_mqtt.rb:2:in `<module:Fluent>': uninitialized constant Fluent::Input (NameError)
	from /var/lib/gems/2.3.0/gems/fluent-plugin-mqtt-io-0.2.3/lib/fluent/plugin/in_mqtt.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/registry.rb:102:in `block in search'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/registry.rb:99:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/registry.rb:99:in `search'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/registry.rb:44:in `lookup'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin.rb:146:in `new_impl'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/plugin.rb:100:in `new_input'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/root_agent.rb:277:in `add_source'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/root_agent.rb:122:in `block in configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/root_agent.rb:118:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/root_agent.rb:118:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/engine.rb:131:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/engine.rb:96:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:770:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:553:in `dry_run'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:571:in `supervise'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/supervisor.rb:476:in `run_supervisor'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-1.1.0/bin/fluentd:8:in `<top (required)>'
	from /usr/local/bin/fluentd:22:in `load'
	from /usr/local/bin/fluentd:22:in `<main>'

**Comment by Montecito** [comment]
Fixed fluentd docker build and configuration.

Verified on hogarma-dev & hogarama-prod
