### ISSUE TITLE
BUG: Error with AMQ on local openshift

### ISSUE THREAD

**Issue by sjutz** [Gepardec/Hogarama#179]

**Comment by ErhardSiegl** [comment]
Is this the following error?
```
2018-09-01 17:18:10,013 INFO  [com.gepardec.hogarama.service.ActorServiceImpl] (EJB default - 6) sendActorMessage: location: Wien, actorName: Mock Sensor, duration: 5
2018-09-01 17:18:10,019 INFO  [com.gepardec.hogarama.mocks.cli.MqttClient] (EJB default - 6) Publising to ssl://broker-amq-mqtt-ssl-hogarama.127.0.0.1.nip.io:8883
2018-09-01 17:18:10,125 ERROR [com.gepardec.hogarama.mocks.cli.MqttClient] (EJB default - 6) Error while publishing : java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.fusesource.hawtdispatch.transport.TcpTransport$2$1$1.run(TcpTransport.java:489)
        at org.fusesource.hawtdispatch.internal.NioDispatchSource$3.run(NioDispatchSource.java:209)
        at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
        at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)
```

**Comment by ErhardSiegl** [comment]
The problem is, that within Openshift, we need to use the service-URL ssl://broker-amq-mqtt-ssl:8883 but in a local JBoss we need to adress the external route https://broker-amq-mqtt-ssl-hogarama.127.0.0.1.nip.io

However we just use a host (AMQ_HOST) and somehow assume we need the service URL
```
	//TODO: hardcoded port replacement should be fixed.
	public MqttClient withHost(String host) {
		this.host = host.replaceAll("https", "ssl");
		this.host = this.host.replaceAll("http", "tcp");
		if(!this.host.matches(PORT_PROVIDED_REGEX)) {
			this.host += ":8883";
		}
		return this;
	}
```
We should use a AMQ_URL instead of AMQ_HOST to avoid the problem. When looking at the source code of org.fusesource.mqtt.client.MQTT we see that what they call host is really a URI:
```
    public void setHost(String host) throws URISyntaxException {
        this.setHost(new URI(host));
    }
```
