### ISSUE TITLE
Performance problem problem processing watering queue

### ISSUE THREAD

**Issue by ErhardSiegl** [Gepardec/Hogarama#323]
On the vienna Installation we have Message Count 19023.
The the processing lags behind several minutes which causes flooding by watering events.

**Comment by ErhardSiegl** [comment]
Problem dürfte daran liegen:
````
        at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:142)
        at org.mongodb.morphia.query.MorphiaIterator.hasNext(MorphiaIterator.java:106)
        at org.mongodb.morphia.query.QueryImpl.asList(QueryImpl.java:147)
        at com.gepardec.hogarama.service.dao.SensorDAOImpl.getLocationBySensorName(SensorDAOImpl.java:99)
        at com.gepardec.hogarama.service.dao.SensorDAOImpl$Proxy$_$$_WeldClientProxy.getLocationBySensorName(Unknown Source)
        at com.gepardec.hogarama.service.ActorServiceImpl.checkParametersOrFail(ActorServiceImpl.java:53)
        at com.gepardec.hogarama.service.ActorServiceImpl.sendActorMessage(ActorServiceImpl.java:33)
        at com.gepardec.hogarama.domain.watering.WateringService.invokeActorIfNeeded(WateringService.java:57)
        at com.gepardec.hogarama.domain.watering.WateringService.water(WateringService.java:78)
        at com.gepardec.hogarama.service.schedulers.WateringMDB.onMessage(WateringMDB.java:53)
```
